[package]
name = "regex-thompson-counting"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "rethoc"
path = "src/main.rs"

[dev-dependencies]
itertools = "0.10"
regex = "1"

[dependencies]
indexmap = "2"
regex-syntax = "0.8.9"
